name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - uses: coursier/setup-action@v3
      with:
        apps: scala-cli
        version: nightly
    - name: Test
      run: scala-cli compile src --server=false

  package:
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - spark: "4.2.0"
          hadoop: "3"
        - spark: "4.1.2"
          hadoop: "3"
        - spark: "4.0.3"
          hadoop: "3"
        - spark: "3.5.8"
          hadoop: "3"
        - spark: "3.4.4"
          hadoop: "3"
        - spark: "3.3.4"
          hadoop: "3"
        - spark: "3.3.4"
          hadoop: "2"
        - spark: "3.2.4"
          hadoop: "3.2"
        - spark: "3.2.4"
          hadoop: "2.7"
        - spark: "3.1.3"
          hadoop: "3.2"
        - spark: "3.1.3"
          hadoop: "2.7"
        - spark: "3.0.3"
          hadoop: "3.2"
        - spark: "3.0.3"
          hadoop: "2.7"
        - spark: "2.4.8"
          hadoop: "2.7"
        - spark: "2.4.2"
          hadoop: "2.7"
    name: package (spark-${{ matrix.spark }}-hadoop${{ matrix.hadoop }})
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - uses: coursier/setup-action@v3
      with:
        apps: scala-cli
        version: nightly
    - name: Create and upload archives
      run: scala-cli run Upload.scala --server=false -- ${{ matrix.spark }} ${{ matrix.hadoop }}
      env:
        UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
