name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - uses: coursier/setup-action@v3
      with:
        apps: scala-cli
    - name: Test
      run: scala-cli compile src --server=false

  package:
    needs: compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - uses: coursier/setup-action@v3
      with:
        apps: scala-cli
    - name: Create and upload archives
      run: scala-cli run Upload.scala --server=false
      env:
        UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
